image: gitpod/workspace-python
tasks:
  - name: install spatialdata universe and dependencies
    command: |
      python -m pip install -e .
      python -m pip install -r requirements-dev.txt
      python -m pip install spatialdata-io spatialdata-plot
      pre-commit install --install-hooks